### ISSUE TITLE
Propose reorg for code Episodes (4&5 of bucket 2)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#109]
This has always been an awkward section with the Quarto version of this workshop due to some oddities of how Quarto works vs RMarkdown. They are also quite long as is.  

I propose splitting up the 2 episodes into 3 with content being changed to: 

**Ep 4: "Adding Code to Quarto Documents"** 
1. Introduction to code in Quarto & Knitr engine
2. Inline code
3. Code Chunks (anatomy and how to run)
4. Dealing with relative path issues in Quarto documents
5. Set working directory in Quarto docs

**Ep. 5 "Rendering code & Yaml options**
1. Intro to Rendering Quarto Docs
2. Code Chunk options 
3. Global Options (document-level)

**Ep 6: " Getting Fancy with Code Chunks"** _optional episode_
1. Global Options (Project level settings ) 
2. Globally loading packages and data
3. Running external Code
5. Other advanced topics? (i.e. YAML options as referenced  in ep. 5 #tip-yaml-chunk-options

**Comment by ilessing** [comment]
I'm in favor of reorganizing the episodes.

**Comment by torwhite** [comment]
Add inline code to ep. 5 between 2 & 3

**Comment by rcurty** [comment]
Working on the reorg...Suggested titles:
"Adding Code to Quarto Documents"
"Rendering Custom Code Outputs" 
"Advanced Chunk Options"
I will push the new versions later today without replacing existing episodes so you can all review them. On Friday, we can make a final decision and remove the old ones. We will have a run-through on Monday to test it in multiple installs and J. Hb.

**Comment by rcurty** [comment]
I've recently uploaded three new episodes following the reorganization, keeping the older versions available until we finalize this iteration. Once we complete the run-through, I'll adjust the timing and renumber the biblio-crossref to 7.

@torwhite, could you kindly review it to ensure it aligns with your vision? I would appreciate your input/clarification on the following points:

- I moved the sequence with the inline code to the end of Ep. 5, instead of in between rendering code and cleaning outputs. I thought it flowed better and respected the transition from code chunks in ep. 4. However, I'm open to your thoughts on this.
- Regarding Global Options (Project-level settings), I'm uncertain about the content meant for inclusion in the new Ep. 6. While Ep. 4 covers the project-level path adjustment, other content focuses on the document level. Please lmk if there's anything I might have missed.
- The development of Tips as advanced options for Ep. 6 might require examples. Initially, I envisioned these at the document level. If applying at the project level, we might need an additional qmd to illustrate the benefits (e.g., applying TOC or section numbering across all documents). Any thoughts on this?
- Are the new titles, questions, and learning objectives good?

**Comment by rcurty** [comment]
Old eps removed.

**Comment by rcurty** [comment]
Changes for this offering were completed.

**Comment by torwhite** [comment]
This looks good. There's room to add additional topics in the Advanced code chunk section but that can be addressed later.
