### ISSUE TITLE
Ep.5 - Include a note to select the quarto branch

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#24]
Add info to choose the quarto branch when importing the project folder.

**Comment by ilessing** [comment]
both @jonjab and @kristi-sara ran into this issue today during our work session/meeting.

It happens when user clones the [examples repo](https://github.com/carpentries-incubator/Reproducible-Publications-with-RStudio-Example) to their local (or Jupyter Hub) environment.  

Then when one looks in the `report` folder there is no `DataPaper-ReproducibilityWorkshop.qmd`

The way to fix this is to change to the `quarto` branch in R-Studio on the Git tab.
