### ISSUE TITLE
Reorg Curriculum

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#47]
Consider breaking the workshop down into 3 parts:
1) Intro to RStudio and Quarto (could even be asynchronous)
2) Create reproducible papers (project examples)
3) Advanced topics (including ep. 8)

**Comment by torwhite** [comment]
Let's make sure to make the next version in Rmd so it's compliant with the future carpentry workbench

**Comment by ilessing** [comment]
consider a reorg to separate sections:

- Planning your pub
    - folder structure
    - Git  setup (fork and clone) - Does this belong here?  This is how we bring in our examples.
- Implement
    - quarto
    - markdown  
    - rendering
- Publish
    - advanced topics
      -  `renv`
      - collaboration with Git & Github (`git push`)

Need to consider further where in the workshop Git fits?  (git gives me fits)

We should consider distributing the Example publication via a zip file in the workshop rather than getting it via git fork and clone.

**Comment by ilessing** [comment]
> Let's make sure to make the next version in Rmd so it's compliant with the future carpentry workbench

made this comment into a separate issue #61

**Comment by ilessing** [comment]
see #79 for new structure proposed for modularization

**Comment by rcurty** [comment]
Reorg completed.
