### ISSUE TITLE
Ep. 3 RStudio tour - compare writing code in console vs Rscript vs qmd

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#65]
Talk more about workflow in writing code in .qmd directly vs console vs separate R script.

Discuss scenarios where one would write & run code in the console vs. rscript vs. qmd

**Comment by rcurty** [comment]
How does this sound?

When writing code in Rstudio, there are different workflows you can use, including writing code directly in the console, using a separate R script, or writing your code in a .qmd file. The best approach depends on your specific needs and preferences:

**1. Writing code directly in the console** is useful for quick calculations. However, keeping track of the code you've written can be challenging, especially if it takes multiple lines. Additionally, if you need to run the same code multiple times, you'll have to rewrite it each time, which can be inconvenient if you plan to reuse it.

**2. Using a separate R script** is a more organized way to write and save code, and you can easily reuse it later or share it with others. If you need to modify the code, you can easily edit and rerun the script. However, running code in a script requires more steps than running code in the console, and it can be more challenging to modify code interactively.

**3. Using a .qmd file** combines the advantages of both the console and R script. A .qmd file allows you to write . R code and text in the same document, which makes it easier to organize and document your work. Additionally, you can run the code directly in the paper, which makes it easier to modify and rerun code interactively. 

We will be using the third approach for most of this workshop since we are focusing on creating a reproducible paper.

**Comment by ilessing** [comment]
suggest adding following...

1. Writing code directly in the console is useful **_when you want to execute code immediately to see the effect of a statement, make a quick change or calculation._**  However, keeping track of the code....

**Comment by rcurty** [comment]
thanks, @ilessing! Added!
