### ISSUE TITLE
Bucket 2 (Quarto) 01-basic-rstudio.md

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#91]
Very likely, some learners won't have packages pre-installed. Provide the line of code in the episode instead of directing them back to the setup instructions.

**Comment by rcurty** [comment]
For in-person workshops, it is best to add it as a note in the lesson.

**Comment by rcurty** [comment]
Note and code added. But to confirm our setup and packages. Do we still need the `here` package?

**Comment by rcurty** [comment]
@torwhite will check

**Comment by rcurty** [comment]
Package `here` is mentioned in https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/02-Quarto/05-code-chunks/index.html

**Comment by torwhite** [comment]
Ah you beat me to it! More specifically, it's found here: https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/02-Quarto/05-code-chunks/index.html#note-r-markdown-method-for-setting-working-directory-also-works-in-quarto  

We can probably take the 'here' package out since it's optional

**Comment by torwhite** [comment]
I think rprojroot may also be removed from the package list similar to 'here' but need to do a double check.

**Comment by rcurty** [comment]
We will remove both packages.

**Comment by rcurty** [comment]
Done. see: https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/commit/6a89906bd523b47c7fd124630d9ed4c1c2571985
